version: '3.8'

services:
  maria_db:
    image: mariadb/server:10.11
    container_name: mariadb-db-container
    restart: always
    networks:
      http-cats-network:
        ipv4_address: 192.168.1.10
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p", "password"]
      interval: 10s
      timeout: 40s
      retries: 5
    ports:
      - "3030:3030"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: http_cats
      MARIADB_USER: http_cats_user
      MARIADB_PASSWORD: password
    volumes:
      - ./http-cats.sql:/docker-entrypoint-initdb.d/http-cats.sql
      - db_data:/var/lib/mariadb

  quarkus_api:
    restart: always
    container_name: http-cats-api-container
    networks:
      http-cats-network:
        ipv4_address: 192.168.1.20
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    depends_on:
      maria_db:
        condition: service_healthy

volumes:
  db_data:

networks:
  http-cats-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24